### ISSUE TITLE
Unit gallery page

### ISSUE THREAD

**Issue by mlutsar** [geocollections/kivid.info#18]
Lehekülg, et näidata kivi juurde käivaid pilte. Peab kuvama pilte leheküljel ning võimaldama full-screen funktsionaalsust.

Pildi juures peaks näitama: autori info, viited pildi ja säiliku unikaalsele url-ile.

Näide mindatist: https://www.mindat.org/g/921
Kasutavad ilmselt seda: http://fancybox.net/

**Comment by mlutsar** [comment]
Kommentaar kliendilt: slideshow vaates võiks veel pildi peal näidata overlayd infoga.

**Comment by liisha** [comment]
Kuna API ei tagasta infot autori ja säiliku kohta, siis pole seda võimaik realiseerida.
